/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class misaka_lab_jni_App */

#ifndef _Included_misaka_lab_jni_App
#define _Included_misaka_lab_jni_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     misaka_lab_jni_App
 * Method:    getGreeting
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_misaka_lab_jni_App_getGreeting
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
